# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSA.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QMainWindow(object):
    def setupUi(self, btn_gen_keys):
        btn_gen_keys.setObjectName("btn_gen_keys")
        btn_gen_keys.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(btn_gen_keys)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 30, 91, 41))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 70, 81, 21))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 41, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 200, 51, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 200, 51, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 120, 51, 20))
        self.label_5.setObjectName("label_5")
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(150, 110, 141, 71))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(150, 200, 141, 71))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.txt_sign = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(420, 200, 141, 71))
        self.txt_sign.setObjectName("txt_sign")
        self.txt_info = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(420, 110, 141, 71))
        self.txt_info.setObjectName("txt_info")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(110, 310, 56, 17))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(250, 310, 56, 17))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(390, 310, 56, 17))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(510, 310, 56, 17))
        self.btn_verify.setObjectName("btn_verify")
        btn_gen_keys.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(btn_gen_keys)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        btn_gen_keys.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(btn_gen_keys)
        self.statusbar.setObjectName("statusbar")
        btn_gen_keys.setStatusBar(self.statusbar)

        self.retranslateUi(btn_gen_keys)
        QtCore.QMetaObject.connectSlotsByName(btn_gen_keys)

    def retranslateUi(self, btn_gen_keys):
        _translate = QtCore.QCoreApplication.translate
        btn_gen_keys.setWindowTitle(_translate("btn_gen_keys", "MainWindow"))
        self.label.setText(_translate("btn_gen_keys", "RSA CIPHER"))
        self.pushButton.setText(_translate("btn_gen_keys", "Generate Keys"))
        self.label_2.setText(_translate("btn_gen_keys", "Plain Text:"))
        self.label_3.setText(_translate("btn_gen_keys", "Cipher Text:"))
        self.label_4.setText(_translate("btn_gen_keys", "Signature:"))
        self.label_5.setText(_translate("btn_gen_keys", "Information:"))
        self.btn_encrypt.setText(_translate("btn_gen_keys", "Encrypt"))
        self.btn_decrypt.setText(_translate("btn_gen_keys", "Decrypt"))
        self.btn_sign.setText(_translate("btn_gen_keys", "Sign"))
        self.btn_verify.setText(_translate("btn_gen_keys", "Verify"))
